<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>date</name>
  <uuid>aff887cd-0f30-4d9e-ae13-bf6860a00c40</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Name is "Broudeur" 
then

add 3/22/2021 to decision ; 
add 5/10/2021 to decision ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
