<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Month 1</name>
  <uuid>e5d0613d-12b8-4476-a657-d97387d8c795</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Name is "Broudeur"
then
	add January to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
