<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Month 2</name>
  <uuid>9738d561-4c5d-47b7-94cd-9fbc9f2849db</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Name is "Broudeur"
then
	add February to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
